### ISSUE TITLE
Create named compressed files

### ISSUE THREAD

**Issue by martyzz1** [django-compressor/django-compressor#621]
I was wondering if it was possible to use the block_name given on the compress template call to "name" the resultant compressed files?

e.g.
{% compress css file main %}
     <link rel="stylesheet" type="text/x-scss" href="{% static 'sass/app.scss' %}">
{% endcompress %}

would result in an output file called 

http://127.0.0.1:8000/static/CACHE/css/main.d64abeaedbad.css

**Comment by martyzz1** [comment]
This also affects the ability to use Django Whitenoise for serving static assets, as whitenoise's inbuilt detection of cache busted files fails because it expects <name>.<hash>.css

I'll try to look into making a patch, but I think this could be quite complex. Any pointers of where to look in the compressor codebase for where filenames are generated would be awesome..

**Comment by furiousdave** [comment]
To pile on this, I'd love the ability to configure compressor to use the hash as a query string at the end of a static filename for cache busting instead of part of the filename itself. That way, the compressed stylesheet could still be loaded into ckeditor or the like. Being able to choose to overwrite a single file might be preferable to some people as well in terms of disk space.

**Comment by alexgustafson** [comment]
yes, bump here. I have exactly that ckeditor use case. I would like to be able to know the exact nyme in advance so that I can add it to the ckeditor configuration, allowing uses to be able to preview the styles in the editor.

**Comment by badeendjuh** [comment]
It seems to me the documentation already says this should happen?
See the last example in in:
https://django-compressor.readthedocs.io/en/latest/usage/#examples

I've found that (with 2.2) this works only for some templates and not others. I've not seen a real pattern.

**Comment by karyon** [comment]
yeah, it seems like this has been implemented in https://github.com/django-compressor/django-compressor/pull/861. @badeendjuh if you could investigate in which cases this does not work, that would be nice.

**Comment by badeendjuh** [comment]
My brain must be playing tricks on me. I'm sure i've seen the file-names as described, but now i'm unable to get those again in my environment.

**Comment by karyon** [comment]
@badeendjuh that would be very weird. it would be nice if you could verify and if the block name does indeed not show up in the file name, please open a new issue.

**Comment by etnbrd** [comment]
Is this feature still implemented ?
I am not getting the expected result:
```
manifest.json 
...
"479c26fbea1f9150a2180b3a1e9a2290d9069c6ff6ae90c499605ac8aa075a55": "<script type=\"text/javascript\" src=\"/__compressor_url_placeholder__/js/e44bebf8eeb3.js\"></script>\n<script type=\"text/javascript\" src=\"/__compressor_url_placeholder__/js/97e2e693fb5c.js\" defer></script>\n<script type=\"text/javascript\" src=\"/__compressor_url_placeholder__/js/af8137d0272b.js\"></script>", 
...
```
I would expect the filename to be `output.e44bebf8eeb3.js` instead of `e44bebf8eeb3.js`.

And I am confused as some parts of the code of the aforementioned PR seem to have disappeared from the code base.

**Comment by karyon** [comment]
yeah, i would expect that as well. which parts did disappear? if you could investigate, that would be nice. i don't have the time right now.

**Comment by etnbrd** [comment]
In the [PR](https://github.com/django-compressor/django-compressor/pull/861/files#diff-d4aadf2becd6919f53d2a6808afb7f09R289)(adding argument `basename`):
```
-    def output(self, mode='file', forced=False):
+    def output(self, mode='file', forced=False, basename=None):
```

While in the code from [tag 2.2](https://github.com/django-compressor/django-compressor/blob/2.2/compressor/base.py#L289)(argument `basename` is not here):
```
 def output(self, mode='file', forced=False):
```

The same in [`master`](https://github.com/django-compressor/django-compressor/blob/master/compressor/base.py#L289).
However, I can see the argument `basename` in branch [`develop`](https://github.com/django-compressor/django-compressor/blob/develop/compressor/base.py#L309).

I installed v2.2, where I expected this change to be (as per what @badeendjuh reported), but in my own `venv`, the code doesn't contains the changes from the PR.
```
$ pip show django-compressor
Name: django-compressor
Version: 2.2
```
So it's consistent with what I observe in `tag 2.2` and `master`.

I see that the PR actually got merged into `develop`, but maybe never made its way to `master` and to the `2.2` release ?
And maybe @badeendjuh installed the `develop` branch instead of `2.2` ?

**Comment by karyon** [comment]
thanks for investigating. the reason is likely that the aforementioned PR has been merged after 2.2 was released, and we haven't had a release since. you can try out the development branch if you need this, that's rather easy with pip.

closing as fixed in #861

**Comment by octavioamu** [comment]
block_name still doesn't change the name of the output file keep naming it output.[hash].js as the docs https://django-compressor.readthedocs.io/en/stable/usage/#examples

**Comment by karyon** [comment]
thanks for the investigation @octavioamu. could you put this into a new issue?
